SELECT A_I.ANIMAL_ID, A_I.ANIMAL_TYPE, A_I.NAME
FROM ANIMAL_INS AS A_I
LEFT OUTER JOIN ANIMAL_OUTS AS A_O
ON A_I.ANIMAL_ID = A_O.ANIMAL_ID
WHERE A_I.SEX_UPON_INTAKE LIKE "Intact %" AND A_O.SEX_UPON_OUTCOME NOT LIKE "Intact %"
ORDER BY A_I.ANIMAL_ID;