SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR
       , B.MSIZE - A.SIZE_OF_COLONY AS YEAR_DEV
       , A.ID AS ID
  FROM ECOLI_DATA
  AS A
  JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
               , MAX(SIZE_OF_COLONY) AS MSIZE
        FROM ECOLI_DATA
        GROUP BY YEAR
       ) B
  ON LEFT(A.DIFFERENTIATION_DATE,4) = B.YEAR
  ORDER BY YEAR, YEAR_DEV;